version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_colegio
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678@
      POSTGRES_DB: sistema_colegio
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: